### ISSUE TITLE
Wanted to give it a try but

### ISSUE THREAD

**Issue by WaGi-Coding** [davepruitt/BetterSerialMonitor#1]
Wanted to give it a try, but it won't detect most of my COM Ports, while the Arduino IDE does (yes i closed the other monitors etc.)

**Comment by davepruitt** [comment]
Sorry for such a late reply, I didn't see your comment until just now.

The code for finding serial ports uses the Windows ManagementObjectSearcher, and it searches for anything classified as a WIN32_SerialPort. Here is the full code snippet:
```
private void Refresh_ports_worker_DoWork(object sender, DoWorkEventArgs e)
{
    lock (_available_devices_lock)
    {
        //Create a list to hold information from USB devices
        List<USBDeviceInfo> devices = new List<USBDeviceInfo>();

        //Query all connected devices
        var searcher = new ManagementObjectSearcher(@"SELECT * FROM WIN32_SerialPort");
        var collection = searcher.Get();

        //Grab the information we need
        foreach (var device in collection)
        {
            string id = (string)device.GetPropertyValue("DeviceID");
            string desc = (string)device.GetPropertyValue("Description");
            USBDeviceInfo d = new USBDeviceInfo(desc, id, false);
            devices.Add(d);
        }

        //Dispose of the collection of queried devices
        collection.Dispose();

        //Set the list of available devices
        _available_devices = devices;
    }
}
```

This code could theoretically be replaced with a call to `SerialPort.GetPortNames()`, but then you would have no information as to which device each COM port represents. As far as I know, the above code should find all the same COM ports as `SerialPort.GetPortNames()`, in addition to providing you extra information about what each COM port is.

**Comment by davepruitt** [comment]
Closing this for now, but I am willing to re-open it if the issue persists.

**Comment by davepruitt** [comment]
Found an issue in not detecting com ports, fixing it now
